name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: "x64"
      - name: Build artifacts
        run: |
          python -m scripts.build

      - name: Test build
        run: |
          pip install dist/*.whl
          pip uninstall -y pdm-pep517
          pip install dist/*.tar.gz
          pip uninstall -y pdm-pep517
      - name: Upload to Pypi
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
